### ISSUE TITLE
how to change auto n = idxs.extract(pos); in c++14

### ISSUE THREAD

**Issue by fatalfeel** [Nuzhny007/Non-Maximum-Suppression#3]
I only have c++14 how to change
auto n = idxs.extract(pos);

**Comment by fatalfeel** [comment]
is this correct?
//auto n = idxs.extract(pos);
					//n.key() = newScore;
					//idxs.insert(std::move(n));
					idxs.insert(std::multimap<float, size_t>::value_type(newScore, pos->second));\
					idxs.erase(pos);
					++pos;

**Comment by Nuzhny007** [comment]
> I only have c++14 how to change auto n = idxs.extract(pos);

Remove old value and insert new. And yes - your code is correct

**Comment by fatalfeel** [comment]
thansk man
